// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RandomLink.proto

package protogen

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RANDOMLINK struct {
	// PRIMARY 识别符
	RandomID string `protobuf:"bytes,1,opt,name=RandomID,proto3" json:"RandomID,omitempty"`
	// PRIMARY 副键
	SubID uint32 `protobuf:"varint,2,opt,name=SubID,proto3" json:"SubID,omitempty"`
	// 保存类型
	SaveType string `protobuf:"bytes,3,opt,name=SaveType,proto3" json:"SaveType,omitempty"`
	// 保存参数
	SaveParam uint64 `protobuf:"varint,4,opt,name=SaveParam,proto3" json:"SaveParam,omitempty"`
	// 实现逻辑类型
	RewardType string `protobuf:"bytes,5,opt,name=RewardType,proto3" json:"RewardType,omitempty"`
	// 条件参数
	Param uint64 `protobuf:"varint,6,opt,name=Param,proto3" json:"Param,omitempty"`
	// 跳转帧
	Goto string `protobuf:"bytes,7,opt,name=Goto,proto3" json:"Goto,omitempty"`
	// 对应表
	GotoPage string `protobuf:"bytes,8,opt,name=GotoPage,proto3" json:"GotoPage,omitempty"`
	// 权数
	Factor uint32 `protobuf:"varint,9,opt,name=Factor,proto3" json:"Factor,omitempty"`
	// 总池区间
	PoolRange []uint32 `protobuf:"varint,10,rep,packed,name=PoolRange,proto3" json:"PoolRange,omitempty"`
	// 权数区间
	WeightRange []uint32 `protobuf:"varint,11,rep,packed,name=WeightRange,proto3" json:"WeightRange,omitempty"`
	// 抽中跳转
	HitLink string `protobuf:"bytes,12,opt,name=HitLink,proto3" json:"HitLink,omitempty"`
	// 未中跳转
	MissLink string `protobuf:"bytes,13,opt,name=MissLink,proto3" json:"MissLink,omitempty"`
	// 条件ID
	ConditionID          uint32   `protobuf:"varint,14,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RANDOMLINK) Reset()         { *m = RANDOMLINK{} }
func (m *RANDOMLINK) String() string { return proto.CompactTextString(m) }
func (*RANDOMLINK) ProtoMessage()    {}
func (*RANDOMLINK) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b5841b25580f2d, []int{0}
}

func (m *RANDOMLINK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RANDOMLINK.Unmarshal(m, b)
}
func (m *RANDOMLINK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RANDOMLINK.Marshal(b, m, deterministic)
}
func (m *RANDOMLINK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RANDOMLINK.Merge(m, src)
}
func (m *RANDOMLINK) XXX_Size() int {
	return xxx_messageInfo_RANDOMLINK.Size(m)
}
func (m *RANDOMLINK) XXX_DiscardUnknown() {
	xxx_messageInfo_RANDOMLINK.DiscardUnknown(m)
}

var xxx_messageInfo_RANDOMLINK proto.InternalMessageInfo

func (m *RANDOMLINK) GetRandomID() string {
	if m != nil {
		return m.RandomID
	}
	return ""
}

func (m *RANDOMLINK) GetSubID() uint32 {
	if m != nil {
		return m.SubID
	}
	return 0
}

func (m *RANDOMLINK) GetSaveType() string {
	if m != nil {
		return m.SaveType
	}
	return ""
}

func (m *RANDOMLINK) GetSaveParam() uint64 {
	if m != nil {
		return m.SaveParam
	}
	return 0
}

func (m *RANDOMLINK) GetRewardType() string {
	if m != nil {
		return m.RewardType
	}
	return ""
}

func (m *RANDOMLINK) GetParam() uint64 {
	if m != nil {
		return m.Param
	}
	return 0
}

func (m *RANDOMLINK) GetGoto() string {
	if m != nil {
		return m.Goto
	}
	return ""
}

func (m *RANDOMLINK) GetGotoPage() string {
	if m != nil {
		return m.GotoPage
	}
	return ""
}

func (m *RANDOMLINK) GetFactor() uint32 {
	if m != nil {
		return m.Factor
	}
	return 0
}

func (m *RANDOMLINK) GetPoolRange() []uint32 {
	if m != nil {
		return m.PoolRange
	}
	return nil
}

func (m *RANDOMLINK) GetWeightRange() []uint32 {
	if m != nil {
		return m.WeightRange
	}
	return nil
}

func (m *RANDOMLINK) GetHitLink() string {
	if m != nil {
		return m.HitLink
	}
	return ""
}

func (m *RANDOMLINK) GetMissLink() string {
	if m != nil {
		return m.MissLink
	}
	return ""
}

func (m *RANDOMLINK) GetConditionID() uint32 {
	if m != nil {
		return m.ConditionID
	}
	return 0
}

type RANDOMLINK_ARRAY struct {
	Items                []*RANDOMLINK `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RANDOMLINK_ARRAY) Reset()         { *m = RANDOMLINK_ARRAY{} }
func (m *RANDOMLINK_ARRAY) String() string { return proto.CompactTextString(m) }
func (*RANDOMLINK_ARRAY) ProtoMessage()    {}
func (*RANDOMLINK_ARRAY) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b5841b25580f2d, []int{1}
}

func (m *RANDOMLINK_ARRAY) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RANDOMLINK_ARRAY.Unmarshal(m, b)
}
func (m *RANDOMLINK_ARRAY) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RANDOMLINK_ARRAY.Marshal(b, m, deterministic)
}
func (m *RANDOMLINK_ARRAY) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RANDOMLINK_ARRAY.Merge(m, src)
}
func (m *RANDOMLINK_ARRAY) XXX_Size() int {
	return xxx_messageInfo_RANDOMLINK_ARRAY.Size(m)
}
func (m *RANDOMLINK_ARRAY) XXX_DiscardUnknown() {
	xxx_messageInfo_RANDOMLINK_ARRAY.DiscardUnknown(m)
}

var xxx_messageInfo_RANDOMLINK_ARRAY proto.InternalMessageInfo

func (m *RANDOMLINK_ARRAY) GetItems() []*RANDOMLINK {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*RANDOMLINK)(nil), "protogen.RANDOMLINK")
	proto.RegisterType((*RANDOMLINK_ARRAY)(nil), "protogen.RANDOMLINK_ARRAY")
}

func init() { proto.RegisterFile("RandomLink.proto", fileDescriptor_65b5841b25580f2d) }

var fileDescriptor_65b5841b25580f2d = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xdf, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xe9, 0xb7, 0xfb, 0x79, 0xf7, 0x9d, 0x8c, 0x30, 0xe4, 0x22, 0x22, 0x61, 0x4f, 0xc5,
	0x87, 0x3d, 0xe8, 0xbb, 0x30, 0x2c, 0x6a, 0x71, 0x9b, 0x23, 0x13, 0xc4, 0x27, 0xc9, 0x5c, 0xa8,
	0x41, 0x97, 0x8c, 0x36, 0x2a, 0xfe, 0x13, 0xfe, 0xcd, 0x92, 0x1b, 0x6b, 0xfb, 0x94, 0x7c, 0xce,
	0x3d, 0xa7, 0x39, 0xf4, 0xc2, 0x48, 0x48, 0xb3, 0xb5, 0xbb, 0xb9, 0x36, 0xaf, 0xd3, 0x7d, 0x61,
	0x9d, 0x65, 0x3d, 0x3a, 0x72, 0x65, 0x26, 0xdf, 0x31, 0x80, 0x98, 0x2d, 0xd3, 0xbb, 0xc5, 0x3c,
	0x5b, 0xde, 0xb2, 0x23, 0xe8, 0x05, 0x73, 0x96, 0x62, 0xc4, 0xa3, 0xa4, 0x2f, 0xfe, 0x98, 0x8d,
	0xa1, 0xbd, 0x7e, 0xdf, 0x64, 0x29, 0xfe, 0xe3, 0x51, 0x32, 0x14, 0x01, 0x7c, 0x62, 0x2d, 0x3f,
	0xd4, 0xfd, 0xd7, 0x5e, 0x61, 0x1c, 0x12, 0x15, 0xb3, 0x63, 0xe8, 0xfb, 0xfb, 0x4a, 0x16, 0x72,
	0x87, 0x2d, 0x1e, 0x25, 0x2d, 0x51, 0x0b, 0xec, 0x04, 0x40, 0xa8, 0x4f, 0x59, 0x6c, 0x29, 0xdb,
	0xa6, 0x6c, 0x43, 0xf1, 0xef, 0x85, 0x64, 0x87, 0x92, 0x01, 0x18, 0x83, 0xd6, 0xb5, 0x75, 0x16,
	0xbb, 0xe4, 0xa7, 0xbb, 0xef, 0xe0, 0xcf, 0x95, 0xcc, 0x15, 0xf6, 0x42, 0x87, 0x8a, 0xd9, 0x21,
	0x74, 0xae, 0xe4, 0xb3, 0xb3, 0x05, 0xf6, 0xa9, 0xf6, 0x2f, 0xf9, 0x6e, 0x2b, 0x6b, 0xdf, 0x84,
	0x34, 0xb9, 0x42, 0xe0, 0x71, 0x32, 0x14, 0xb5, 0xc0, 0x38, 0x0c, 0x1e, 0x94, 0xce, 0x5f, 0x5c,
	0x98, 0x0f, 0x68, 0xde, 0x94, 0x18, 0x42, 0xf7, 0x46, 0x3b, 0xff, 0x4f, 0xf1, 0x3f, 0x3d, 0x59,
	0xa1, 0x6f, 0xb3, 0xd0, 0x65, 0x49, 0xa3, 0x61, 0x68, 0x53, 0xb1, 0xff, 0xee, 0xa5, 0x35, 0x5b,
	0xed, 0xb4, 0x35, 0x59, 0x8a, 0x07, 0x54, 0xa9, 0x29, 0x4d, 0x2e, 0x60, 0x54, 0xef, 0xe3, 0x69,
	0x26, 0xc4, 0xec, 0x91, 0x9d, 0x42, 0x5b, 0x3b, 0xb5, 0x2b, 0x31, 0xe2, 0x71, 0x32, 0x38, 0x1b,
	0x4f, 0xab, 0xf5, 0x4d, 0x6b, 0xab, 0x08, 0x96, 0x4d, 0x87, 0x66, 0xe7, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x83, 0xaf, 0xe8, 0x1b, 0xf5, 0x01, 0x00, 0x00,
}
