// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/g_s.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_CommonScene             MsgType = 0 // 场景线内操作。
	MsgType_EnterScene              MsgType = 1 // 进入新的场景线。
	MsgType_ForceEnterScene         MsgType = 2 // 强制进入新的场景线（不受场景线人数限制控制）。
	MsgType_GetSceneLine            MsgType = 3 // 获取场景分线信息。
	MsgType_ChangeSceneLine         MsgType = 4 // 切换场景分线预占位。
	MsgType_GetSceneLineNotRealTime MsgType = 5 // 获取场景分线信息（非实时）。
	MsgType_NpcEnterScene           MsgType = 6 //npc 出生
	MsgType_NpcLeaveScene           MsgType = 7 //npc 销毁
	MsgType_GetNpcList              MsgType = 8 //npc 列表
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "CommonScene",
		1: "EnterScene",
		2: "ForceEnterScene",
		3: "GetSceneLine",
		4: "ChangeSceneLine",
		5: "GetSceneLineNotRealTime",
		6: "NpcEnterScene",
		7: "NpcLeaveScene",
		8: "GetNpcList",
	}
	MsgType_value = map[string]int32{
		"CommonScene":             0,
		"EnterScene":              1,
		"ForceEnterScene":         2,
		"GetSceneLine":            3,
		"ChangeSceneLine":         4,
		"GetSceneLineNotRealTime": 5,
		"NpcEnterScene":           6,
		"NpcLeaveScene":           7,
		"GetNpcList":              8,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_g_s_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_proto_g_s_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_g_s_proto_rawDescGZIP(), []int{0}
}

// 尝试场景线占位。
type TrySceneSeizeSeat int32

const (
	TrySceneSeizeSeat_Success TrySceneSeizeSeat = 0 // 目标场景线占位成功（有效期5S）。
	TrySceneSeizeSeat_Fail    TrySceneSeizeSeat = 1 // 目标场景线占位失败。
	TrySceneSeizeSeat_NotExit TrySceneSeizeSeat = 2 // 目标场景线不存在。
)

// Enum value maps for TrySceneSeizeSeat.
var (
	TrySceneSeizeSeat_name = map[int32]string{
		0: "Success",
		1: "Fail",
		2: "NotExit",
	}
	TrySceneSeizeSeat_value = map[string]int32{
		"Success": 0,
		"Fail":    1,
		"NotExit": 2,
	}
)

func (x TrySceneSeizeSeat) Enum() *TrySceneSeizeSeat {
	p := new(TrySceneSeizeSeat)
	*p = x
	return p
}

func (x TrySceneSeizeSeat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrySceneSeizeSeat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_g_s_proto_enumTypes[1].Descriptor()
}

func (TrySceneSeizeSeat) Type() protoreflect.EnumType {
	return &file_proto_g_s_proto_enumTypes[1]
}

func (x TrySceneSeizeSeat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrySceneSeizeSeat.Descriptor instead.
func (TrySceneSeizeSeat) EnumDescriptor() ([]byte, []int) {
	return file_proto_g_s_proto_rawDescGZIP(), []int{1}
}

type SceneMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId         string              `protobuf:"bytes,1,opt,name=sceneId,proto3" json:"sceneId,omitempty"`                         // 场景线ID。
	Acids           []string            `protobuf:"bytes,2,rep,name=acids,proto3" json:"acids,omitempty"`                             // 玩家的ACIDs。
	ShardId         uint32              `protobuf:"varint,3,opt,name=shardId,proto3" json:"shardId,omitempty"`                        // GameX的ID。
	MsgId           uint32              `protobuf:"varint,4,opt,name=msgId,proto3" json:"msgId,omitempty"`                            // Msg的反射ID。
	MsgData         []byte              `protobuf:"bytes,5,opt,name=msgData,proto3" json:"msgData,omitempty"`                         // Msg的内容。
	MsgType         MsgType             `protobuf:"varint,6,opt,name=msgType,proto3,enum=proto.MsgType" json:"msgType,omitempty"`     // 消息的类型。
	ErrDes          string              `protobuf:"bytes,7,opt,name=errDes,proto3" json:"errDes,omitempty"`                           // 异常信息描述。
	OnlySetPosition bool                `protobuf:"varint,8,opt,name=onlySetPosition,proto3" json:"onlySetPosition,omitempty"`        // 传送时使用，仅设置位置，不改变场景线。
	Code            TrySceneSeizeSeat   `protobuf:"varint,9,opt,name=Code,proto3,enum=proto.TrySceneSeizeSeat" json:"Code,omitempty"` // 试图切线占位的结果。
	SceLineRoleNum  []*SceneLineRoleNum `protobuf:"bytes,10,rep,name=SceLineRoleNum,proto3" json:"SceLineRoleNum,omitempty"`          // 场景线的信息。
	AllLineNpc      *AllLineNpcInfo     `protobuf:"bytes,11,opt,name=allLineNpc,proto3" json:"allLineNpc,omitempty"`                  //全线显示的npc
	NpcUniqId       string              `protobuf:"bytes,12,opt,name=npcUniqId,proto3" json:"npcUniqId,omitempty"`                    // npcid
	AllLineNpcList  []string            `protobuf:"bytes,13,rep,name=allLineNpcList,proto3" json:"allLineNpcList,omitempty"`          //全线显示的npc列表
	Ctx             []byte              `protobuf:"bytes,14,opt,name=ctx,proto3" json:"ctx,omitempty"`                                // 链路追踪context
	WarzoneId       int32               `protobuf:"varint,15,opt,name=warzoneId,proto3" json:"warzoneId,omitempty"`                   // 战区ID，跨服场景使用
	IsAllLineNpc    bool                `protobuf:"varint,16,opt,name=isAllLineNpc,proto3" json:"isAllLineNpc,omitempty"`             //是否每个线上都要有
}

func (x *SceneMsg) Reset() {
	*x = SceneMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_g_s_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneMsg) ProtoMessage() {}

func (x *SceneMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_g_s_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneMsg.ProtoReflect.Descriptor instead.
func (*SceneMsg) Descriptor() ([]byte, []int) {
	return file_proto_g_s_proto_rawDescGZIP(), []int{0}
}

func (x *SceneMsg) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *SceneMsg) GetAcids() []string {
	if x != nil {
		return x.Acids
	}
	return nil
}

func (x *SceneMsg) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *SceneMsg) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SceneMsg) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *SceneMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_CommonScene
}

func (x *SceneMsg) GetErrDes() string {
	if x != nil {
		return x.ErrDes
	}
	return ""
}

func (x *SceneMsg) GetOnlySetPosition() bool {
	if x != nil {
		return x.OnlySetPosition
	}
	return false
}

func (x *SceneMsg) GetCode() TrySceneSeizeSeat {
	if x != nil {
		return x.Code
	}
	return TrySceneSeizeSeat_Success
}

func (x *SceneMsg) GetSceLineRoleNum() []*SceneLineRoleNum {
	if x != nil {
		return x.SceLineRoleNum
	}
	return nil
}

func (x *SceneMsg) GetAllLineNpc() *AllLineNpcInfo {
	if x != nil {
		return x.AllLineNpc
	}
	return nil
}

func (x *SceneMsg) GetNpcUniqId() string {
	if x != nil {
		return x.NpcUniqId
	}
	return ""
}

func (x *SceneMsg) GetAllLineNpcList() []string {
	if x != nil {
		return x.AllLineNpcList
	}
	return nil
}

func (x *SceneMsg) GetCtx() []byte {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *SceneMsg) GetWarzoneId() int32 {
	if x != nil {
		return x.WarzoneId
	}
	return 0
}

func (x *SceneMsg) GetIsAllLineNpc() bool {
	if x != nil {
		return x.IsAllLineNpc
	}
	return false
}

type AllLineNpcInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectType int32  `protobuf:"varint,1,opt,name=ObjectType,proto3" json:"ObjectType,omitempty"`
	ConfigId   int32  `protobuf:"varint,2,opt,name=ConfigId,proto3" json:"ConfigId,omitempty"`
	DeadTime   int64  `protobuf:"varint,3,opt,name=DeadTime,proto3" json:"DeadTime,omitempty"`  // 死亡时间
	OwnerName  string `protobuf:"bytes,4,opt,name=OwnerName,proto3" json:"OwnerName,omitempty"` //归属者名字
	OwnerAcid  string `protobuf:"bytes,5,opt,name=OwnerAcid,proto3" json:"OwnerAcid,omitempty"` //归属者id
	PosX       int32  `protobuf:"varint,6,opt,name=PosX,proto3" json:"PosX,omitempty"`
	PosZ       int32  `protobuf:"varint,7,opt,name=PosZ,proto3" json:"PosZ,omitempty"`
	UniqId     string `protobuf:"bytes,8,opt,name=UniqId,proto3" json:"UniqId,omitempty"` //唯一id
}

func (x *AllLineNpcInfo) Reset() {
	*x = AllLineNpcInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_g_s_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllLineNpcInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLineNpcInfo) ProtoMessage() {}

func (x *AllLineNpcInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_g_s_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLineNpcInfo.ProtoReflect.Descriptor instead.
func (*AllLineNpcInfo) Descriptor() ([]byte, []int) {
	return file_proto_g_s_proto_rawDescGZIP(), []int{1}
}

func (x *AllLineNpcInfo) GetObjectType() int32 {
	if x != nil {
		return x.ObjectType
	}
	return 0
}

func (x *AllLineNpcInfo) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *AllLineNpcInfo) GetDeadTime() int64 {
	if x != nil {
		return x.DeadTime
	}
	return 0
}

func (x *AllLineNpcInfo) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *AllLineNpcInfo) GetOwnerAcid() string {
	if x != nil {
		return x.OwnerAcid
	}
	return ""
}

func (x *AllLineNpcInfo) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *AllLineNpcInfo) GetPosZ() int32 {
	if x != nil {
		return x.PosZ
	}
	return 0
}

func (x *AllLineNpcInfo) GetUniqId() string {
	if x != nil {
		return x.UniqId
	}
	return ""
}

type SceneLineRoleNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceLine       uint32   `protobuf:"varint,1,opt,name=SceLine,proto3" json:"SceLine,omitempty"`
	SceRoleNum    uint32   `protobuf:"varint,2,opt,name=SceRoleNum,proto3" json:"SceRoleNum,omitempty"`
	SceRoleMaxNum uint32   `protobuf:"varint,3,opt,name=SceRoleMaxNum,proto3" json:"SceRoleMaxNum,omitempty"`
	Extra         []uint32 `protobuf:"varint,4,rep,packed,name=extra,proto3" json:"extra,omitempty"`
}

func (x *SceneLineRoleNum) Reset() {
	*x = SceneLineRoleNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_g_s_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneLineRoleNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneLineRoleNum) ProtoMessage() {}

func (x *SceneLineRoleNum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_g_s_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneLineRoleNum.ProtoReflect.Descriptor instead.
func (*SceneLineRoleNum) Descriptor() ([]byte, []int) {
	return file_proto_g_s_proto_rawDescGZIP(), []int{2}
}

func (x *SceneLineRoleNum) GetSceLine() uint32 {
	if x != nil {
		return x.SceLine
	}
	return 0
}

func (x *SceneLineRoleNum) GetSceRoleNum() uint32 {
	if x != nil {
		return x.SceRoleNum
	}
	return 0
}

func (x *SceneLineRoleNum) GetSceRoleMaxNum() uint32 {
	if x != nil {
		return x.SceRoleMaxNum
	}
	return 0
}

func (x *SceneLineRoleNum) GetExtra() []uint32 {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_proto_g_s_proto protoreflect.FileDescriptor

var file_proto_g_s_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x5f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x04, 0x0a, 0x08, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x63, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x63, 0x69, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x28, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x44, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x44, 0x65,
	0x73, 0x12, 0x28, 0x0a, 0x0f, 0x6f, 0x6e, 0x6c, 0x79, 0x53, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x6f, 0x6e, 0x6c, 0x79,
	0x53, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x72, 0x79, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x53, 0x65, 0x69, 0x7a, 0x65, 0x53,
	0x65, 0x61, 0x74, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x3f, 0x0a, 0x0e, 0x53, 0x63, 0x65,
	0x4c, 0x69, 0x6e, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4c,
	0x69, 0x6e, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x0e, 0x53, 0x63, 0x65, 0x4c,
	0x69, 0x6e, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x35, 0x0a, 0x0a, 0x61, 0x6c,
	0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x70, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x70,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x70,
	0x63, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x70, 0x63, 0x55, 0x6e, 0x69, 0x71, 0x49, 0x64, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x70, 0x63, 0x55, 0x6e, 0x69, 0x71, 0x49, 0x64, 0x12,
	0x26, 0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x70, 0x63, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x65,
	0x4e, 0x70, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x74, 0x78, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x63, 0x74, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x61, 0x72,
	0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x77, 0x61,
	0x72, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x41, 0x6c, 0x6c,
	0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x70, 0x63, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69,
	0x73, 0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x70, 0x63, 0x22, 0xe4, 0x01, 0x0a, 0x0e,
	0x41, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x70, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e,
	0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65,
	0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x65,
	0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x41, 0x63, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x41, 0x63,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x58, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x50, 0x6f, 0x73, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x5a, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x5a, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x6e,
	0x69, 0x71, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x6e, 0x69, 0x71,
	0x49, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x10, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4c, 0x69, 0x6e, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63, 0x65, 0x4c, 0x69,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x53, 0x63, 0x65, 0x4c, 0x69, 0x6e,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x63, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x53, 0x63, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x75,
	0x6d, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x63, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4d, 0x61, 0x78, 0x4e,
	0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x53, 0x63, 0x65, 0x52, 0x6f, 0x6c,
	0x65, 0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x2a, 0xb9, 0x01,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x46, 0x6f,
	0x72, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x10,
	0x03, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x4c, 0x69, 0x6e, 0x65, 0x10, 0x04, 0x12, 0x1b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x70, 0x63, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x70, 0x63, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x4e, 0x70, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x10, 0x08, 0x2a, 0x37, 0x0a, 0x11, 0x54, 0x72, 0x79,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x53, 0x65, 0x69, 0x7a, 0x65, 0x53, 0x65, 0x61, 0x74, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46,
	0x61, 0x69, 0x6c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x74,
	0x10, 0x02, 0x32, 0x70, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12,
	0x32, 0x0a, 0x08, 0x4f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x1a, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x12, 0x2f, 0x0a, 0x09, 0x4f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x73,
	0x67, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4d,
	0x73, 0x67, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x74,
	0x61, 0x69, 0x79, 0x6f, 0x75, 0x78, 0x69, 0x2e, 0x63, 0x6e, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_g_s_proto_rawDescOnce sync.Once
	file_proto_g_s_proto_rawDescData = file_proto_g_s_proto_rawDesc
)

func file_proto_g_s_proto_rawDescGZIP() []byte {
	file_proto_g_s_proto_rawDescOnce.Do(func() {
		file_proto_g_s_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_g_s_proto_rawDescData)
	})
	return file_proto_g_s_proto_rawDescData
}

var file_proto_g_s_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_g_s_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_g_s_proto_goTypes = []interface{}{
	(MsgType)(0),             // 0: proto.MsgType
	(TrySceneSeizeSeat)(0),   // 1: proto.TrySceneSeizeSeat
	(*SceneMsg)(nil),         // 2: proto.SceneMsg
	(*AllLineNpcInfo)(nil),   // 3: proto.AllLineNpcInfo
	(*SceneLineRoleNum)(nil), // 4: proto.SceneLineRoleNum
}
var file_proto_g_s_proto_depIdxs = []int32{
	0, // 0: proto.SceneMsg.msgType:type_name -> proto.MsgType
	1, // 1: proto.SceneMsg.Code:type_name -> proto.TrySceneSeizeSeat
	4, // 2: proto.SceneMsg.SceLineRoleNum:type_name -> proto.SceneLineRoleNum
	3, // 3: proto.SceneMsg.allLineNpc:type_name -> proto.AllLineNpcInfo
	2, // 4: proto.GameScene.OnStream:input_type -> proto.SceneMsg
	2, // 5: proto.GameScene.OnCommand:input_type -> proto.SceneMsg
	2, // 6: proto.GameScene.OnStream:output_type -> proto.SceneMsg
	2, // 7: proto.GameScene.OnCommand:output_type -> proto.SceneMsg
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_g_s_proto_init() }
func file_proto_g_s_proto_init() {
	if File_proto_g_s_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_g_s_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_g_s_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllLineNpcInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_g_s_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneLineRoleNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_g_s_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_g_s_proto_goTypes,
		DependencyIndexes: file_proto_g_s_proto_depIdxs,
		EnumInfos:         file_proto_g_s_proto_enumTypes,
		MessageInfos:      file_proto_g_s_proto_msgTypes,
	}.Build()
	File_proto_g_s_proto = out.File
	file_proto_g_s_proto_rawDesc = nil
	file_proto_g_s_proto_goTypes = nil
	file_proto_g_s_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GameSceneClient is the client API for GameScene service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameSceneClient interface {
	OnStream(ctx context.Context, opts ...grpc.CallOption) (GameScene_OnStreamClient, error)
	OnCommand(ctx context.Context, in *SceneMsg, opts ...grpc.CallOption) (*SceneMsg, error)
}

type gameSceneClient struct {
	cc grpc.ClientConnInterface
}

func NewGameSceneClient(cc grpc.ClientConnInterface) GameSceneClient {
	return &gameSceneClient{cc}
}

func (c *gameSceneClient) OnStream(ctx context.Context, opts ...grpc.CallOption) (GameScene_OnStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GameScene_serviceDesc.Streams[0], "/proto.GameScene/OnStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameSceneOnStreamClient{stream}
	return x, nil
}

type GameScene_OnStreamClient interface {
	Send(*SceneMsg) error
	Recv() (*SceneMsg, error)
	grpc.ClientStream
}

type gameSceneOnStreamClient struct {
	grpc.ClientStream
}

func (x *gameSceneOnStreamClient) Send(m *SceneMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameSceneOnStreamClient) Recv() (*SceneMsg, error) {
	m := new(SceneMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameSceneClient) OnCommand(ctx context.Context, in *SceneMsg, opts ...grpc.CallOption) (*SceneMsg, error) {
	out := new(SceneMsg)
	err := c.cc.Invoke(ctx, "/proto.GameScene/OnCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameSceneServer is the server API for GameScene service.
type GameSceneServer interface {
	OnStream(GameScene_OnStreamServer) error
	OnCommand(context.Context, *SceneMsg) (*SceneMsg, error)
}

// UnimplementedGameSceneServer can be embedded to have forward compatible implementations.
type UnimplementedGameSceneServer struct {
}

func (*UnimplementedGameSceneServer) OnStream(GameScene_OnStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method OnStream not implemented")
}
func (*UnimplementedGameSceneServer) OnCommand(context.Context, *SceneMsg) (*SceneMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnCommand not implemented")
}

func RegisterGameSceneServer(s *grpc.Server, srv GameSceneServer) {
	s.RegisterService(&_GameScene_serviceDesc, srv)
}

func _GameScene_OnStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameSceneServer).OnStream(&gameSceneOnStreamServer{stream})
}

type GameScene_OnStreamServer interface {
	Send(*SceneMsg) error
	Recv() (*SceneMsg, error)
	grpc.ServerStream
}

type gameSceneOnStreamServer struct {
	grpc.ServerStream
}

func (x *gameSceneOnStreamServer) Send(m *SceneMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameSceneOnStreamServer) Recv() (*SceneMsg, error) {
	m := new(SceneMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GameScene_OnCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SceneMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSceneServer).OnCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GameScene/OnCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSceneServer).OnCommand(ctx, req.(*SceneMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameScene_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GameScene",
	HandlerType: (*GameSceneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnCommand",
			Handler:    _GameScene_OnCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnStream",
			Handler:       _GameScene_OnStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/g_s.proto",
}
