// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/m_gm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单个gamex的信息
type ShardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 大区号
	Gid int32 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	// server id
	Sid int32 `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	// 唯一合服ID
	MergeUID int32 `protobuf:"varint,3,opt,name=mergeUID,proto3" json:"mergeUID,omitempty"`
	// 回滚mergeUID，仅回滚使用
	PreMergeUID int32 `protobuf:"varint,4,opt,name=preMergeUID,proto3" json:"preMergeUID,omitempty"`
	// ip地址，关闭和启动gamex用
	Ip string `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	// scene ip地址, 关闭和启动scene使用
	SceneIP string `protobuf:"bytes,6,opt,name=sceneIP,proto3" json:"sceneIP,omitempty"`
	// 合服时server id对应的子服(没合过服就是sid本身)
	SubShard []uint32 `protobuf:"varint,7,rep,packed,name=subShard,proto3" json:"subShard,omitempty"`
}

func (x *ShardInfo) Reset() {
	*x = ShardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInfo) ProtoMessage() {}

func (x *ShardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInfo.ProtoReflect.Descriptor instead.
func (*ShardInfo) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{0}
}

func (x *ShardInfo) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ShardInfo) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ShardInfo) GetMergeUID() int32 {
	if x != nil {
		return x.MergeUID
	}
	return 0
}

func (x *ShardInfo) GetPreMergeUID() int32 {
	if x != nil {
		return x.PreMergeUID
	}
	return 0
}

func (x *ShardInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ShardInfo) GetSceneIP() string {
	if x != nil {
		return x.SceneIP
	}
	return ""
}

func (x *ShardInfo) GetSubShard() []uint32 {
	if x != nil {
		return x.SubShard
	}
	return nil
}

// 开始合服请求
type StartMergeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 合服目标，即合到哪个服
	Target *ShardInfo `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// 合服来源，即之前的哪几个服合
	Sources []*ShardInfo `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	// 完成合服后的回调地址
	CallbackAddr string `protobuf:"bytes,3,opt,name=callbackAddr,proto3" json:"callbackAddr,omitempty"`
}

func (x *StartMergeReq) Reset() {
	*x = StartMergeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMergeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMergeReq) ProtoMessage() {}

func (x *StartMergeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMergeReq.ProtoReflect.Descriptor instead.
func (*StartMergeReq) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{1}
}

func (x *StartMergeReq) GetTarget() *ShardInfo {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *StartMergeReq) GetSources() []*ShardInfo {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *StartMergeReq) GetCallbackAddr() string {
	if x != nil {
		return x.CallbackAddr
	}
	return ""
}

// 开始合服回复
type StartMergeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否成功开始
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *StartMergeResp) Reset() {
	*x = StartMergeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMergeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMergeResp) ProtoMessage() {}

func (x *StartMergeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMergeResp.ProtoReflect.Descriptor instead.
func (*StartMergeResp) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{2}
}

func (x *StartMergeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartMergeResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// 查询状态请求
type QueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否查询当前merger所有进度状态
	IsAll bool `protobuf:"varint,1,opt,name=isAll,proto3" json:"isAll,omitempty"`
	// server id
	Sid int32 `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *QueryReq) Reset() {
	*x = QueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReq) ProtoMessage() {}

func (x *QueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReq.ProtoReflect.Descriptor instead.
func (*QueryReq) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{3}
}

func (x *QueryReq) GetIsAll() bool {
	if x != nil {
		return x.IsAll
	}
	return false
}

func (x *QueryReq) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

// 查询状态回复
type QueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sps []*ShardProgress `protobuf:"bytes,1,rep,name=sps,proto3" json:"sps,omitempty"`
}

func (x *QueryResp) Reset() {
	*x = QueryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResp) ProtoMessage() {}

func (x *QueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResp.ProtoReflect.Descriptor instead.
func (*QueryResp) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResp) GetSps() []*ShardProgress {
	if x != nil {
		return x.Sps
	}
	return nil
}

// 单个gamex的合服进度
type ShardProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// shard ID
	Sid int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	// 合服唯一ID
	MergeUID int32 `protobuf:"varint,2,opt,name=mergeUID,proto3" json:"mergeUID,omitempty"`
	// 操作类型，合服、回滚...
	OpType string `protobuf:"bytes,3,opt,name=opType,proto3" json:"opType,omitempty"`
	// 本次合服是否成功
	IsSuccess bool `protobuf:"varint,4,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	// 本次合服是否完成
	IsFinish bool `protobuf:"varint,5,opt,name=isFinish,proto3" json:"isFinish,omitempty"`
	// 模块合服进度
	MPs []*ModuleProgress `protobuf:"bytes,6,rep,name=MPs,proto3" json:"MPs,omitempty"`
	// 当前进度
	CurMP *ModuleProgress `protobuf:"bytes,7,opt,name=CurMP,proto3" json:"CurMP,omitempty"`
}

func (x *ShardProgress) Reset() {
	*x = ShardProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardProgress) ProtoMessage() {}

func (x *ShardProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardProgress.ProtoReflect.Descriptor instead.
func (*ShardProgress) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{5}
}

func (x *ShardProgress) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ShardProgress) GetMergeUID() int32 {
	if x != nil {
		return x.MergeUID
	}
	return 0
}

func (x *ShardProgress) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *ShardProgress) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *ShardProgress) GetIsFinish() bool {
	if x != nil {
		return x.IsFinish
	}
	return false
}

func (x *ShardProgress) GetMPs() []*ModuleProgress {
	if x != nil {
		return x.MPs
	}
	return nil
}

func (x *ShardProgress) GetCurMP() *ModuleProgress {
	if x != nil {
		return x.CurMP
	}
	return nil
}

// 合服进度
type ModuleProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 模块名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 是否成功
	IsSuccess bool `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	// 开始时间戳
	StartTime int64 `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// 结束时间戳
	EndTime int64 `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	// 附加信息
	Msg string `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ModuleProgress) Reset() {
	*x = ModuleProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleProgress) ProtoMessage() {}

func (x *ModuleProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleProgress.ProtoReflect.Descriptor instead.
func (*ModuleProgress) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{6}
}

func (x *ModuleProgress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleProgress) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *ModuleProgress) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ModuleProgress) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ModuleProgress) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ResetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetReq) Reset() {
	*x = ResetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetReq) ProtoMessage() {}

func (x *ResetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetReq.ProtoReflect.Descriptor instead.
func (*ResetReq) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{7}
}

type ResetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否成功开始
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *ResetResp) Reset() {
	*x = ResetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResp) ProtoMessage() {}

func (x *ResetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResp.ProtoReflect.Descriptor instead.
func (*ResetResp) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{8}
}

func (x *ResetResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type RollbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 回滚目标，对应新生成的参数
	Target *ShardInfo `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// 回滚来源，对应合服前的参数
	Sources []*ShardInfo `protobuf:"bytes,4,rep,name=sources,proto3" json:"sources,omitempty"`
	// 完成合服后的回调地址
	CallbackAddr string `protobuf:"bytes,5,opt,name=callbackAddr,proto3" json:"callbackAddr,omitempty"`
}

func (x *RollbackReq) Reset() {
	*x = RollbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackReq) ProtoMessage() {}

func (x *RollbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackReq.ProtoReflect.Descriptor instead.
func (*RollbackReq) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{9}
}

func (x *RollbackReq) GetTarget() *ShardInfo {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RollbackReq) GetSources() []*ShardInfo {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *RollbackReq) GetCallbackAddr() string {
	if x != nil {
		return x.CallbackAddr
	}
	return ""
}

type RollbackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否成功开始
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *RollbackResp) Reset() {
	*x = RollbackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_m_gm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResp) ProtoMessage() {}

func (x *RollbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_m_gm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResp.ProtoReflect.Descriptor instead.
func (*RollbackResp) Descriptor() ([]byte, []int) {
	return file_proto_m_gm_proto_rawDescGZIP(), []int{10}
}

func (x *RollbackResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_proto_m_gm_proto protoreflect.FileDescriptor

var file_proto_m_gm_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x5f, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xb3, 0x01, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x72, 0x67,
	0x65, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x65, 0x72, 0x67,
	0x65, 0x55, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x4d, 0x65, 0x72, 0x67, 0x65,
	0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x4d, 0x65,
	0x72, 0x67, 0x65, 0x55, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49,
	0x50, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x50,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x53, 0x68, 0x61, 0x72, 0x64, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x08, 0x73, 0x75, 0x62, 0x53, 0x68, 0x61, 0x72, 0x64, 0x22, 0x83, 0x01, 0x0a,
	0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x25,
	0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x64,
	0x64, 0x72, 0x22, 0x42, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x65, 0x72, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x32, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x41, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x69, 0x73, 0x41, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x09, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x03, 0x73, 0x70, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x03, 0x73, 0x70, 0x73, 0x22, 0xdf, 0x01, 0x0a,
	0x0d, 0x53, 0x68, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x55, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x24,
	0x0a, 0x03, 0x4d, 0x50, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x03, 0x4d, 0x50, 0x73, 0x12, 0x28, 0x0a, 0x05, 0x43, 0x75, 0x72, 0x4d, 0x50, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x05, 0x43, 0x75, 0x72, 0x4d, 0x50, 0x22, 0x8c,
	0x01, 0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x22, 0x3d, 0x0a, 0x09, 0x72, 0x65, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x81, 0x01, 0x0a, 0x0b, 0x72, 0x6f, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12,
	0x27, 0x0a, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x22, 0x40, 0x0a, 0x0c,
	0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x32, 0xb3,
	0x01, 0x0a, 0x06, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x65, 0x72,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x24, 0x0a, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x65,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x73, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x74,
	0x61, 0x69, 0x79, 0x6f, 0x75, 0x78, 0x69, 0x2e, 0x63, 0x6e, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_m_gm_proto_rawDescOnce sync.Once
	file_proto_m_gm_proto_rawDescData = file_proto_m_gm_proto_rawDesc
)

func file_proto_m_gm_proto_rawDescGZIP() []byte {
	file_proto_m_gm_proto_rawDescOnce.Do(func() {
		file_proto_m_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_m_gm_proto_rawDescData)
	})
	return file_proto_m_gm_proto_rawDescData
}

var file_proto_m_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_m_gm_proto_goTypes = []interface{}{
	(*ShardInfo)(nil),      // 0: pb.ShardInfo
	(*StartMergeReq)(nil),  // 1: pb.startMergeReq
	(*StartMergeResp)(nil), // 2: pb.startMergeResp
	(*QueryReq)(nil),       // 3: pb.queryReq
	(*QueryResp)(nil),      // 4: pb.queryResp
	(*ShardProgress)(nil),  // 5: pb.ShardProgress
	(*ModuleProgress)(nil), // 6: pb.ModuleProgress
	(*ResetReq)(nil),       // 7: pb.resetReq
	(*ResetResp)(nil),      // 8: pb.resetResp
	(*RollbackReq)(nil),    // 9: pb.rollbackReq
	(*RollbackResp)(nil),   // 10: pb.rollbackResp
}
var file_proto_m_gm_proto_depIdxs = []int32{
	0,  // 0: pb.startMergeReq.target:type_name -> pb.ShardInfo
	0,  // 1: pb.startMergeReq.sources:type_name -> pb.ShardInfo
	5,  // 2: pb.queryResp.sps:type_name -> pb.ShardProgress
	6,  // 3: pb.ShardProgress.MPs:type_name -> pb.ModuleProgress
	6,  // 4: pb.ShardProgress.CurMP:type_name -> pb.ModuleProgress
	0,  // 5: pb.rollbackReq.target:type_name -> pb.ShardInfo
	0,  // 6: pb.rollbackReq.sources:type_name -> pb.ShardInfo
	1,  // 7: pb.Merger.start:input_type -> pb.startMergeReq
	3,  // 8: pb.Merger.query:input_type -> pb.queryReq
	7,  // 9: pb.Merger.reset:input_type -> pb.resetReq
	9,  // 10: pb.Merger.rollback:input_type -> pb.rollbackReq
	2,  // 11: pb.Merger.start:output_type -> pb.startMergeResp
	4,  // 12: pb.Merger.query:output_type -> pb.queryResp
	8,  // 13: pb.Merger.reset:output_type -> pb.resetResp
	10, // 14: pb.Merger.rollback:output_type -> pb.rollbackResp
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_m_gm_proto_init() }
func file_proto_m_gm_proto_init() {
	if File_proto_m_gm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_m_gm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_m_gm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMergeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_m_gm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMergeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_m_gm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_m_gm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_m_gm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_m_gm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_m_gm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_m_gm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_m_gm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_m_gm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollbackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_m_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_m_gm_proto_goTypes,
		DependencyIndexes: file_proto_m_gm_proto_depIdxs,
		MessageInfos:      file_proto_m_gm_proto_msgTypes,
	}.Build()
	File_proto_m_gm_proto = out.File
	file_proto_m_gm_proto_rawDesc = nil
	file_proto_m_gm_proto_goTypes = nil
	file_proto_m_gm_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MergerClient is the client API for Merger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MergerClient interface {
	// 开始合服/回滚
	Start(ctx context.Context, in *StartMergeReq, opts ...grpc.CallOption) (*StartMergeResp, error)
	// 查询进度
	Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error)
	// 重置缓存
	Reset(ctx context.Context, in *ResetReq, opts ...grpc.CallOption) (*ResetResp, error)
	// 回滚
	Rollback(ctx context.Context, in *RollbackReq, opts ...grpc.CallOption) (*RollbackResp, error)
}

type mergerClient struct {
	cc grpc.ClientConnInterface
}

func NewMergerClient(cc grpc.ClientConnInterface) MergerClient {
	return &mergerClient{cc}
}

func (c *mergerClient) Start(ctx context.Context, in *StartMergeReq, opts ...grpc.CallOption) (*StartMergeResp, error) {
	out := new(StartMergeResp)
	err := c.cc.Invoke(ctx, "/pb.Merger/start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergerClient) Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error) {
	out := new(QueryResp)
	err := c.cc.Invoke(ctx, "/pb.Merger/query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergerClient) Reset(ctx context.Context, in *ResetReq, opts ...grpc.CallOption) (*ResetResp, error) {
	out := new(ResetResp)
	err := c.cc.Invoke(ctx, "/pb.Merger/reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergerClient) Rollback(ctx context.Context, in *RollbackReq, opts ...grpc.CallOption) (*RollbackResp, error) {
	out := new(RollbackResp)
	err := c.cc.Invoke(ctx, "/pb.Merger/rollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MergerServer is the server API for Merger service.
type MergerServer interface {
	// 开始合服/回滚
	Start(context.Context, *StartMergeReq) (*StartMergeResp, error)
	// 查询进度
	Query(context.Context, *QueryReq) (*QueryResp, error)
	// 重置缓存
	Reset(context.Context, *ResetReq) (*ResetResp, error)
	// 回滚
	Rollback(context.Context, *RollbackReq) (*RollbackResp, error)
}

// UnimplementedMergerServer can be embedded to have forward compatible implementations.
type UnimplementedMergerServer struct {
}

func (*UnimplementedMergerServer) Start(context.Context, *StartMergeReq) (*StartMergeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedMergerServer) Query(context.Context, *QueryReq) (*QueryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedMergerServer) Reset(context.Context, *ResetReq) (*ResetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (*UnimplementedMergerServer) Rollback(context.Context, *RollbackReq) (*RollbackResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}

func RegisterMergerServer(s *grpc.Server, srv MergerServer) {
	s.RegisterService(&_Merger_serviceDesc, srv)
}

func _Merger_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMergeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merger/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergerServer).Start(ctx, req.(*StartMergeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merger_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergerServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merger/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergerServer).Query(ctx, req.(*QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merger_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergerServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merger/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergerServer).Reset(ctx, req.(*ResetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merger_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergerServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merger/Rollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergerServer).Rollback(ctx, req.(*RollbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Merger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Merger",
	HandlerType: (*MergerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "start",
			Handler:    _Merger_Start_Handler,
		},
		{
			MethodName: "query",
			Handler:    _Merger_Query_Handler,
		},
		{
			MethodName: "reset",
			Handler:    _Merger_Reset_Handler,
		},
		{
			MethodName: "rollback",
			Handler:    _Merger_Rollback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/m_gm.proto",
}
