//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/packet.proto
namespace pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientPacket")]
  public partial class ClientPacket : global::ProtoBuf.IExtensible
  {
    public ClientPacket() {}
    
    private int _packetId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"packetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int packetId
    {
      get { return _packetId; }
      set { _packetId = value; }
    }
    private uint _messageId = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"messageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint messageId
    {
      get { return _messageId; }
      set { _messageId = value; }
    }
    private bool _compress = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"compress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool compress
    {
      get { return _compress; }
      set { _compress = value; }
    }
    private byte[] _rawData = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rawData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] rawData
    {
      get { return _rawData; }
      set { _rawData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}