// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kick_push.proto

/*
Package protogen is a generated protocol buffer package.

It is generated from these files:
	kick_push.proto

It has these top-level messages:
	KickPush
*/
package protogen

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KickPush struct {
	Msg              *string `protobuf:"bytes,1,req,name=Msg" json:"Msg,omitempty"`
	After            *int32  `protobuf:"varint,2,req,name=After" json:"After,omitempty"`
	NoLogin          *int32  `protobuf:"varint,3,req,name=NoLogin" json:"NoLogin,omitempty"`
	KickErrCode      *int32  `protobuf:"varint,4,req,name=KickErrCode" json:"KickErrCode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KickPush) Reset()                    { *m = KickPush{} }
func (m *KickPush) String() string            { return proto.CompactTextString(m) }
func (*KickPush) ProtoMessage()               {}
func (*KickPush) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KickPush) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *KickPush) GetAfter() int32 {
	if m != nil && m.After != nil {
		return *m.After
	}
	return 0
}

func (m *KickPush) GetNoLogin() int32 {
	if m != nil && m.NoLogin != nil {
		return *m.NoLogin
	}
	return 0
}

func (m *KickPush) GetKickErrCode() int32 {
	if m != nil && m.KickErrCode != nil {
		return *m.KickErrCode
	}
	return 0
}

func init() {
	proto.RegisterType((*KickPush)(nil), "protogen.KickPush")
}

func init() { proto.RegisterFile("kick_push.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xce, 0x4c, 0xce,
	0x8e, 0x2f, 0x28, 0x2d, 0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xe9,
	0xa9, 0x79, 0x4a, 0x79, 0x5c, 0x1c, 0xde, 0x99, 0xc9, 0xd9, 0x01, 0xa5, 0xc5, 0x19, 0x42, 0x02,
	0x5c, 0xcc, 0xbe, 0xc5, 0xe9, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x08,
	0x17, 0xab, 0x63, 0x5a, 0x49, 0x6a, 0x91, 0x04, 0x93, 0x02, 0x93, 0x06, 0x6b, 0x10, 0x84, 0x23,
	0x24, 0xc1, 0xc5, 0xee, 0x97, 0xef, 0x93, 0x9f, 0x9e, 0x99, 0x27, 0xc1, 0x0c, 0x16, 0x87, 0x71,
	0x85, 0x14, 0xb8, 0xb8, 0x41, 0xa6, 0xb9, 0x16, 0x15, 0x39, 0xe7, 0xa7, 0xa4, 0x4a, 0xb0, 0x80,
	0x65, 0x91, 0x85, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xbe, 0xeb, 0xaa, 0x8b, 0x00, 0x00,
	0x00,
}
