# must be unique in a given SonarQube instance
sonar.projectKey=share
# this is the name and version displayed in the SonarQube UI. Was mandatory prior to SonarQube 6.1.
sonar.projectName=share
sonar.projectVersion=0.0.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
sonar.sources=x,planx
sonar.inclusions=**/**.go
sonar.exclusions=**/examples/**,**.pb.go,**.toml
 
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.language=go

sonar.go.tests.reportPaths=./report/share_test.out
sonar.go.coverage.reportPaths=./report/share_coverage.out
sonar.go.govet.reportPaths=./report/share_vet.out
sonar.go.golint.reportPaths=./report/share_lint.out
# sonar.go.gometalinter.reportPaths=./report/jws2_metalinter.out

