// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: silence_wrapper.proto

package planxprotogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSilenceSysInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId uint32 `protobuf:"varint,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
}

func (x *GetSilenceSysInfoReq) Reset() {
	*x = GetSilenceSysInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silence_wrapper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSilenceSysInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSilenceSysInfoReq) ProtoMessage() {}

func (x *GetSilenceSysInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_silence_wrapper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSilenceSysInfoReq.ProtoReflect.Descriptor instead.
func (*GetSilenceSysInfoReq) Descriptor() ([]byte, []int) {
	return file_silence_wrapper_proto_rawDescGZIP(), []int{0}
}

func (x *GetSilenceSysInfoReq) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type GetSilenceSysInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SilenceSysInfos map[string]int64 `protobuf:"bytes,1,rep,name=silenceSysInfos,proto3" json:"silenceSysInfos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // <acid, endTime>
	Err             string           `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GetSilenceSysInfoResp) Reset() {
	*x = GetSilenceSysInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silence_wrapper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSilenceSysInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSilenceSysInfoResp) ProtoMessage() {}

func (x *GetSilenceSysInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_silence_wrapper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSilenceSysInfoResp.ProtoReflect.Descriptor instead.
func (*GetSilenceSysInfoResp) Descriptor() ([]byte, []int) {
	return file_silence_wrapper_proto_rawDescGZIP(), []int{1}
}

func (x *GetSilenceSysInfoResp) GetSilenceSysInfos() map[string]int64 {
	if x != nil {
		return x.SilenceSysInfos
	}
	return nil
}

func (x *GetSilenceSysInfoResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type SendSilenceSysInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId uint32 `protobuf:"varint,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
	Acid    string `protobuf:"bytes,2,opt,name=acid,proto3" json:"acid,omitempty"`
	EndTime int64  `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	IsBan   bool   `protobuf:"varint,4,opt,name=isBan,proto3" json:"isBan,omitempty"`
}

func (x *SendSilenceSysInfoReq) Reset() {
	*x = SendSilenceSysInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silence_wrapper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSilenceSysInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSilenceSysInfoReq) ProtoMessage() {}

func (x *SendSilenceSysInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_silence_wrapper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSilenceSysInfoReq.ProtoReflect.Descriptor instead.
func (*SendSilenceSysInfoReq) Descriptor() ([]byte, []int) {
	return file_silence_wrapper_proto_rawDescGZIP(), []int{2}
}

func (x *SendSilenceSysInfoReq) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *SendSilenceSysInfoReq) GetAcid() string {
	if x != nil {
		return x.Acid
	}
	return ""
}

func (x *SendSilenceSysInfoReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SendSilenceSysInfoReq) GetIsBan() bool {
	if x != nil {
		return x.IsBan
	}
	return false
}

type SendSilenceSysInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ShardId uint32 `protobuf:"varint,2,opt,name=shardId,proto3" json:"shardId,omitempty"`
	RetMsg  string `protobuf:"bytes,3,opt,name=retMsg,proto3" json:"retMsg,omitempty"`
}

func (x *SendSilenceSysInfoResp) Reset() {
	*x = SendSilenceSysInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silence_wrapper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSilenceSysInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSilenceSysInfoResp) ProtoMessage() {}

func (x *SendSilenceSysInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_silence_wrapper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSilenceSysInfoResp.ProtoReflect.Descriptor instead.
func (*SendSilenceSysInfoResp) Descriptor() ([]byte, []int) {
	return file_silence_wrapper_proto_rawDescGZIP(), []int{3}
}

func (x *SendSilenceSysInfoResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendSilenceSysInfoResp) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *SendSilenceSysInfoResp) GetRetMsg() string {
	if x != nil {
		return x.RetMsg
	}
	return ""
}

var File_silence_wrapper_proto protoreflect.FileDescriptor

var file_silence_wrapper_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x79, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64,
	0x22, 0xca, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x53,
	0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5b, 0x0a, 0x0f, 0x73, 0x69,
	0x6c, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x2e, 0x53, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x53,
	0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a, 0x42, 0x0a, 0x14, 0x53, 0x69, 0x6c,
	0x65, 0x6e, 0x63, 0x65, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x75, 0x0a,
	0x15, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x79, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x63, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x73, 0x42, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69,
	0x73, 0x42, 0x61, 0x6e, 0x22, 0x64, 0x0a, 0x16, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x69, 0x6c, 0x65,
	0x6e, 0x63, 0x65, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x61, 0x69, 0x79, 0x6f, 0x75, 0x78, 0x69, 0x2e, 0x63, 0x6e,
	0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f,
	0x70, 0x6c, 0x61, 0x6e, 0x78, 0x2f, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x79,
	0x73, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_silence_wrapper_proto_rawDescOnce sync.Once
	file_silence_wrapper_proto_rawDescData = file_silence_wrapper_proto_rawDesc
)

func file_silence_wrapper_proto_rawDescGZIP() []byte {
	file_silence_wrapper_proto_rawDescOnce.Do(func() {
		file_silence_wrapper_proto_rawDescData = protoimpl.X.CompressGZIP(file_silence_wrapper_proto_rawDescData)
	})
	return file_silence_wrapper_proto_rawDescData
}

var file_silence_wrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_silence_wrapper_proto_goTypes = []interface{}{
	(*GetSilenceSysInfoReq)(nil),   // 0: proto.GetSilenceSysInfoReq
	(*GetSilenceSysInfoResp)(nil),  // 1: proto.GetSilenceSysInfoResp
	(*SendSilenceSysInfoReq)(nil),  // 2: proto.SendSilenceSysInfoReq
	(*SendSilenceSysInfoResp)(nil), // 3: proto.SendSilenceSysInfoResp
	nil,                            // 4: proto.GetSilenceSysInfoResp.SilenceSysInfosEntry
}
var file_silence_wrapper_proto_depIdxs = []int32{
	4, // 0: proto.GetSilenceSysInfoResp.silenceSysInfos:type_name -> proto.GetSilenceSysInfoResp.SilenceSysInfosEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_silence_wrapper_proto_init() }
func file_silence_wrapper_proto_init() {
	if File_silence_wrapper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_silence_wrapper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSilenceSysInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silence_wrapper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSilenceSysInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silence_wrapper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendSilenceSysInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silence_wrapper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendSilenceSysInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_silence_wrapper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_silence_wrapper_proto_goTypes,
		DependencyIndexes: file_silence_wrapper_proto_depIdxs,
		MessageInfos:      file_silence_wrapper_proto_msgTypes,
	}.Build()
	File_silence_wrapper_proto = out.File
	file_silence_wrapper_proto_rawDesc = nil
	file_silence_wrapper_proto_goTypes = nil
	file_silence_wrapper_proto_depIdxs = nil
}
