
[GateConfig]
etcd_endpoint = ["http://127.0.0.1:2379/"]
etcd_devops = "root/devops"
etcd_server = "root/server"

serverid = "gatex1"

elbaddr=[]
LSBDeadLine = 10

gid=12
publicip="185.238.251.18:8667"           #[prod] 生产环境："aws"
internalip="127.0.0.1"
listen = "185.238.251.18:8667"                    #[prod] 如果gate直接面向公网进行服务则需要公网IP，必须完整ip:port
maxconn = 3
game_conn_num=10
CloudGAAddress="" # 实际对外暴露的地址，用于负载均衡，空就用用publicip

ChatxRedisAddr="127.0.0.1:6379"
ChatxRedisDb="0"
ChatxRedisDbPwd=""

[GateConfig.SslCfg]
cert = ""
key = ""
ca = ""
#cert = "conf/server.crt"
#key = "conf/server.key"
#ca = "conf/ca.crt"

[GateConfig.HostSslCfg] # 正式的证书.
cert = ""
key = ""
ca = ""
host = ""        # 对外的公网域名

[CCUMetricsConfig]
LoginConnector_tick_time = 6

