// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/g_bc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleCheckMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *BattleCheckMsg) Reset() {
	*x = BattleCheckMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_g_bc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleCheckMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleCheckMsg) ProtoMessage() {}

func (x *BattleCheckMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_g_bc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleCheckMsg.ProtoReflect.Descriptor instead.
func (*BattleCheckMsg) Descriptor() ([]byte, []int) {
	return file_proto_g_bc_proto_rawDescGZIP(), []int{0}
}

func (x *BattleCheckMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_g_bc_proto protoreflect.FileDescriptor

var file_proto_g_bc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x5f, 0x62, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x22, 0x0a, 0x0e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x32, 0x4b, 0x0a, 0x0f, 0x47, 0x61,
	0x6d, 0x65, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x38, 0x0a,
	0x08, 0x4f, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x1a, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x73,
	0x67, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x74, 0x61, 0x69, 0x79, 0x6f, 0x75, 0x78, 0x69, 0x2e, 0x63, 0x6e, 0x2f, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x78, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_g_bc_proto_rawDescOnce sync.Once
	file_proto_g_bc_proto_rawDescData = file_proto_g_bc_proto_rawDesc
)

func file_proto_g_bc_proto_rawDescGZIP() []byte {
	file_proto_g_bc_proto_rawDescOnce.Do(func() {
		file_proto_g_bc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_g_bc_proto_rawDescData)
	})
	return file_proto_g_bc_proto_rawDescData
}

var file_proto_g_bc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_g_bc_proto_goTypes = []interface{}{
	(*BattleCheckMsg)(nil), // 0: pb.BattleCheckMsg
}
var file_proto_g_bc_proto_depIdxs = []int32{
	0, // 0: pb.GameBattleCheck.OnPacket:input_type -> pb.BattleCheckMsg
	0, // 1: pb.GameBattleCheck.OnPacket:output_type -> pb.BattleCheckMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_g_bc_proto_init() }
func file_proto_g_bc_proto_init() {
	if File_proto_g_bc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_g_bc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleCheckMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_g_bc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_g_bc_proto_goTypes,
		DependencyIndexes: file_proto_g_bc_proto_depIdxs,
		MessageInfos:      file_proto_g_bc_proto_msgTypes,
	}.Build()
	File_proto_g_bc_proto = out.File
	file_proto_g_bc_proto_rawDesc = nil
	file_proto_g_bc_proto_goTypes = nil
	file_proto_g_bc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GameBattleCheckClient is the client API for GameBattleCheck service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameBattleCheckClient interface {
	OnPacket(ctx context.Context, opts ...grpc.CallOption) (GameBattleCheck_OnPacketClient, error)
}

type gameBattleCheckClient struct {
	cc grpc.ClientConnInterface
}

func NewGameBattleCheckClient(cc grpc.ClientConnInterface) GameBattleCheckClient {
	return &gameBattleCheckClient{cc}
}

func (c *gameBattleCheckClient) OnPacket(ctx context.Context, opts ...grpc.CallOption) (GameBattleCheck_OnPacketClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GameBattleCheck_serviceDesc.Streams[0], "/pb.GameBattleCheck/OnPacket", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameBattleCheckOnPacketClient{stream}
	return x, nil
}

type GameBattleCheck_OnPacketClient interface {
	Send(*BattleCheckMsg) error
	Recv() (*BattleCheckMsg, error)
	grpc.ClientStream
}

type gameBattleCheckOnPacketClient struct {
	grpc.ClientStream
}

func (x *gameBattleCheckOnPacketClient) Send(m *BattleCheckMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameBattleCheckOnPacketClient) Recv() (*BattleCheckMsg, error) {
	m := new(BattleCheckMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameBattleCheckServer is the server API for GameBattleCheck service.
type GameBattleCheckServer interface {
	OnPacket(GameBattleCheck_OnPacketServer) error
}

// UnimplementedGameBattleCheckServer can be embedded to have forward compatible implementations.
type UnimplementedGameBattleCheckServer struct {
}

func (*UnimplementedGameBattleCheckServer) OnPacket(GameBattleCheck_OnPacketServer) error {
	return status.Errorf(codes.Unimplemented, "method OnPacket not implemented")
}

func RegisterGameBattleCheckServer(s *grpc.Server, srv GameBattleCheckServer) {
	s.RegisterService(&_GameBattleCheck_serviceDesc, srv)
}

func _GameBattleCheck_OnPacket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameBattleCheckServer).OnPacket(&gameBattleCheckOnPacketServer{stream})
}

type GameBattleCheck_OnPacketServer interface {
	Send(*BattleCheckMsg) error
	Recv() (*BattleCheckMsg, error)
	grpc.ServerStream
}

type gameBattleCheckOnPacketServer struct {
	grpc.ServerStream
}

func (x *gameBattleCheckOnPacketServer) Send(m *BattleCheckMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameBattleCheckOnPacketServer) Recv() (*BattleCheckMsg, error) {
	m := new(BattleCheckMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GameBattleCheck_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GameBattleCheck",
	HandlerType: (*GameBattleCheckServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnPacket",
			Handler:       _GameBattleCheck_OnPacket_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/g_bc.proto",
}
