// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: dynamic_scene_handler.proto

package planxprotogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamicSceneCmdTyp int32

const (
	DynamicSceneCmdTyp_SLNone              DynamicSceneCmdTyp = 0
	DynamicSceneCmdTyp_SLGetPlayerPosition DynamicSceneCmdTyp = 1 // 获取坐标点信息
	DynamicSceneCmdTyp_SLAsyncMsg          DynamicSceneCmdTyp = 2 // 向场景服发送通知
)

// Enum value maps for DynamicSceneCmdTyp.
var (
	DynamicSceneCmdTyp_name = map[int32]string{
		0: "SLNone",
		1: "SLGetPlayerPosition",
		2: "SLAsyncMsg",
	}
	DynamicSceneCmdTyp_value = map[string]int32{
		"SLNone":              0,
		"SLGetPlayerPosition": 1,
		"SLAsyncMsg":          2,
	}
)

func (x DynamicSceneCmdTyp) Enum() *DynamicSceneCmdTyp {
	p := new(DynamicSceneCmdTyp)
	*p = x
	return p
}

func (x DynamicSceneCmdTyp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DynamicSceneCmdTyp) Descriptor() protoreflect.EnumDescriptor {
	return file_dynamic_scene_handler_proto_enumTypes[0].Descriptor()
}

func (DynamicSceneCmdTyp) Type() protoreflect.EnumType {
	return &file_dynamic_scene_handler_proto_enumTypes[0]
}

func (x DynamicSceneCmdTyp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DynamicSceneCmdTyp.Descriptor instead.
func (DynamicSceneCmdTyp) EnumDescriptor() ([]byte, []int) {
	return file_dynamic_scene_handler_proto_rawDescGZIP(), []int{0}
}

type DynamicSceneCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Typ DynamicSceneCmdTyp `protobuf:"varint,1,opt,name=Typ,proto3,enum=planxproto.DynamicSceneCmdTyp" json:"Typ,omitempty"`
	Msg []byte             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DynamicSceneCmd) Reset() {
	*x = DynamicSceneCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_scene_handler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicSceneCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicSceneCmd) ProtoMessage() {}

func (x *DynamicSceneCmd) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_scene_handler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicSceneCmd.ProtoReflect.Descriptor instead.
func (*DynamicSceneCmd) Descriptor() ([]byte, []int) {
	return file_dynamic_scene_handler_proto_rawDescGZIP(), []int{0}
}

func (x *DynamicSceneCmd) GetTyp() DynamicSceneCmdTyp {
	if x != nil {
		return x.Typ
	}
	return DynamicSceneCmdTyp_SLNone
}

func (x *DynamicSceneCmd) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type DynamicSceneRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg      string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RespInfo [][]byte `protobuf:"bytes,3,rep,name=RespInfo,proto3" json:"RespInfo,omitempty"`
}

func (x *DynamicSceneRet) Reset() {
	*x = DynamicSceneRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_scene_handler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicSceneRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicSceneRet) ProtoMessage() {}

func (x *DynamicSceneRet) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_scene_handler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicSceneRet.ProtoReflect.Descriptor instead.
func (*DynamicSceneRet) Descriptor() ([]byte, []int) {
	return file_dynamic_scene_handler_proto_rawDescGZIP(), []int{1}
}

func (x *DynamicSceneRet) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DynamicSceneRet) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DynamicSceneRet) GetRespInfo() [][]byte {
	if x != nil {
		return x.RespInfo
	}
	return nil
}

var File_dynamic_scene_handler_proto protoreflect.FileDescriptor

var file_dynamic_scene_handler_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70,
	0x6c, 0x61, 0x6e, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x0f, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x30, 0x0a, 0x03,
	0x54, 0x79, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x6c, 0x61, 0x6e,
	0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x43, 0x6d, 0x64, 0x54, 0x79, 0x70, 0x52, 0x03, 0x54, 0x79, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x53, 0x0a, 0x0f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x52, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x49, 0x0a, 0x12, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x43, 0x6d, 0x64, 0x54, 0x79, 0x70, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x4c, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x4c, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x4c, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x10, 0x02,
	0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x74, 0x61, 0x69, 0x79, 0x6f,
	0x75, 0x78, 0x69, 0x2e, 0x63, 0x6e, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x78, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dynamic_scene_handler_proto_rawDescOnce sync.Once
	file_dynamic_scene_handler_proto_rawDescData = file_dynamic_scene_handler_proto_rawDesc
)

func file_dynamic_scene_handler_proto_rawDescGZIP() []byte {
	file_dynamic_scene_handler_proto_rawDescOnce.Do(func() {
		file_dynamic_scene_handler_proto_rawDescData = protoimpl.X.CompressGZIP(file_dynamic_scene_handler_proto_rawDescData)
	})
	return file_dynamic_scene_handler_proto_rawDescData
}

var file_dynamic_scene_handler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dynamic_scene_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dynamic_scene_handler_proto_goTypes = []interface{}{
	(DynamicSceneCmdTyp)(0), // 0: planxproto.DynamicSceneCmdTyp
	(*DynamicSceneCmd)(nil), // 1: planxproto.DynamicSceneCmd
	(*DynamicSceneRet)(nil), // 2: planxproto.DynamicSceneRet
}
var file_dynamic_scene_handler_proto_depIdxs = []int32{
	0, // 0: planxproto.DynamicSceneCmd.Typ:type_name -> planxproto.DynamicSceneCmdTyp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dynamic_scene_handler_proto_init() }
func file_dynamic_scene_handler_proto_init() {
	if File_dynamic_scene_handler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dynamic_scene_handler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicSceneCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_scene_handler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicSceneRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dynamic_scene_handler_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dynamic_scene_handler_proto_goTypes,
		DependencyIndexes: file_dynamic_scene_handler_proto_depIdxs,
		EnumInfos:         file_dynamic_scene_handler_proto_enumTypes,
		MessageInfos:      file_dynamic_scene_handler_proto_msgTypes,
	}.Build()
	File_dynamic_scene_handler_proto = out.File
	file_dynamic_scene_handler_proto_rawDesc = nil
	file_dynamic_scene_handler_proto_goTypes = nil
	file_dynamic_scene_handler_proto_depIdxs = nil
}
