// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/team/team_enum.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 队伍状态
type TeamState int32

const (
	TeamState_TSDefault     TeamState = 1 // 创建完成后进入默认状态
	TeamState_TSMatchUpload TeamState = 2 // 队员上传自己的数据状态。
	TeamState_TSMatching    TeamState = 3 // 匹配中。
	TeamState_TSConfirm     TeamState = 4 // 匹配确认阶段。
	TeamState_TSInBattle    TeamState = 5 // 战斗中。
	TeamState_TSInActive    TeamState = 6 // 不活跃状态。
)

// Enum value maps for TeamState.
var (
	TeamState_name = map[int32]string{
		1: "TSDefault",
		2: "TSMatchUpload",
		3: "TSMatching",
		4: "TSConfirm",
		5: "TSInBattle",
		6: "TSInActive",
	}
	TeamState_value = map[string]int32{
		"TSDefault":     1,
		"TSMatchUpload": 2,
		"TSMatching":    3,
		"TSConfirm":     4,
		"TSInBattle":    5,
		"TSInActive":    6,
	}
)

func (x TeamState) Enum() *TeamState {
	p := new(TeamState)
	*p = x
	return p
}

func (x TeamState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_team_team_enum_proto_enumTypes[0].Descriptor()
}

func (TeamState) Type() protoreflect.EnumType {
	return &file_proto_team_team_enum_proto_enumTypes[0]
}

func (x TeamState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TeamState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TeamState(num)
	return nil
}

// Deprecated: Use TeamState.Descriptor instead.
func (TeamState) EnumDescriptor() ([]byte, []int) {
	return file_proto_team_team_enum_proto_rawDescGZIP(), []int{0}
}

// 队员类型
type MemberType int32

const (
	// 队长
	MemberType_MTLeader MemberType = 1
	// 成员
	MemberType_MTMember MemberType = 2
	// 跨服成员
	MemberType_MTCrossMember MemberType = 3
)

// Enum value maps for MemberType.
var (
	MemberType_name = map[int32]string{
		1: "MTLeader",
		2: "MTMember",
		3: "MTCrossMember",
	}
	MemberType_value = map[string]int32{
		"MTLeader":      1,
		"MTMember":      2,
		"MTCrossMember": 3,
	}
)

func (x MemberType) Enum() *MemberType {
	p := new(MemberType)
	*p = x
	return p
}

func (x MemberType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_team_team_enum_proto_enumTypes[1].Descriptor()
}

func (MemberType) Type() protoreflect.EnumType {
	return &file_proto_team_team_enum_proto_enumTypes[1]
}

func (x MemberType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MemberType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MemberType(num)
	return nil
}

// Deprecated: Use MemberType.Descriptor instead.
func (MemberType) EnumDescriptor() ([]byte, []int) {
	return file_proto_team_team_enum_proto_rawDescGZIP(), []int{1}
}

// 队员状态
type MemberState int32

const (
	//
	MemberState_MSIdle MemberState = 1
	// 跟随
	MemberState_MSFollowing MemberState = 2
	// 离线状态
	MemberState_MSLeave MemberState = 3
)

// Enum value maps for MemberState.
var (
	MemberState_name = map[int32]string{
		1: "MSIdle",
		2: "MSFollowing",
		3: "MSLeave",
	}
	MemberState_value = map[string]int32{
		"MSIdle":      1,
		"MSFollowing": 2,
		"MSLeave":     3,
	}
)

func (x MemberState) Enum() *MemberState {
	p := new(MemberState)
	*p = x
	return p
}

func (x MemberState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_team_team_enum_proto_enumTypes[2].Descriptor()
}

func (MemberState) Type() protoreflect.EnumType {
	return &file_proto_team_team_enum_proto_enumTypes[2]
}

func (x MemberState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MemberState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MemberState(num)
	return nil
}

// Deprecated: Use MemberState.Descriptor instead.
func (MemberState) EnumDescriptor() ([]byte, []int) {
	return file_proto_team_team_enum_proto_rawDescGZIP(), []int{2}
}

// 队伍类型
type TeamType int32

const (
	// 战斗外队伍
	TeamType_TTNormal TeamType = 1
	// 临时队伍
	TeamType_TTTemporary TeamType = 2
)

// Enum value maps for TeamType.
var (
	TeamType_name = map[int32]string{
		1: "TTNormal",
		2: "TTTemporary",
	}
	TeamType_value = map[string]int32{
		"TTNormal":    1,
		"TTTemporary": 2,
	}
)

func (x TeamType) Enum() *TeamType {
	p := new(TeamType)
	*p = x
	return p
}

func (x TeamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_team_team_enum_proto_enumTypes[3].Descriptor()
}

func (TeamType) Type() protoreflect.EnumType {
	return &file_proto_team_team_enum_proto_enumTypes[3]
}

func (x TeamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TeamType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TeamType(num)
	return nil
}

// Deprecated: Use TeamType.Descriptor instead.
func (TeamType) EnumDescriptor() ([]byte, []int) {
	return file_proto_team_team_enum_proto_rawDescGZIP(), []int{3}
}

var File_proto_team_team_enum_proto protoreflect.FileDescriptor

var file_proto_team_team_enum_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x2f, 0x74, 0x65, 0x61,
	0x6d, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65,
	0x61, 0x6d, 0x2a, 0x6c, 0x0a, 0x09, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x0d, 0x0a, 0x09, 0x54, 0x53, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x01, 0x12, 0x11,
	0x0a, 0x0d, 0x54, 0x53, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x10,
	0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x53, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x10,
	0x03, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x53, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x04,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x53, 0x49, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x10, 0x05,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x53, 0x49, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x06,
	0x2a, 0x3b, 0x0a, 0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c,
	0x0a, 0x08, 0x4d, 0x54, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x4d, 0x54, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x54,
	0x43, 0x72, 0x6f, 0x73, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x03, 0x2a, 0x37, 0x0a,
	0x0b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x4d, 0x53, 0x49, 0x64, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x53, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x53, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x10, 0x03, 0x2a, 0x29, 0x0a, 0x08, 0x54, 0x65, 0x61, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x54, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x54, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x10,
	0x02, 0x42, 0x2d, 0x5a, 0x2b, 0x76, 0x63, 0x73, 0x2e, 0x74, 0x61, 0x69, 0x79, 0x6f, 0x75, 0x78,
	0x69, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x6a, 0x77, 0x73, 0x32, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e,
}

var (
	file_proto_team_team_enum_proto_rawDescOnce sync.Once
	file_proto_team_team_enum_proto_rawDescData = file_proto_team_team_enum_proto_rawDesc
)

func file_proto_team_team_enum_proto_rawDescGZIP() []byte {
	file_proto_team_team_enum_proto_rawDescOnce.Do(func() {
		file_proto_team_team_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_team_team_enum_proto_rawDescData)
	})
	return file_proto_team_team_enum_proto_rawDescData
}

var file_proto_team_team_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_team_team_enum_proto_goTypes = []interface{}{
	(TeamState)(0),   // 0: team.TeamState
	(MemberType)(0),  // 1: team.MemberType
	(MemberState)(0), // 2: team.MemberState
	(TeamType)(0),    // 3: team.TeamType
}
var file_proto_team_team_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_team_team_enum_proto_init() }
func file_proto_team_team_enum_proto_init() {
	if File_proto_team_team_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_team_team_enum_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_team_team_enum_proto_goTypes,
		DependencyIndexes: file_proto_team_team_enum_proto_depIdxs,
		EnumInfos:         file_proto_team_team_enum_proto_enumTypes,
	}.Build()
	File_proto_team_team_enum_proto = out.File
	file_proto_team_team_enum_proto_rawDesc = nil
	file_proto_team_team_enum_proto_goTypes = nil
	file_proto_team_team_enum_proto_depIdxs = nil
}
