// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/util.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 位置
type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *int32 `protobuf:"varint,1,req,name=X" json:"X,omitempty"`
	Y *int32 `protobuf:"varint,2,req,name=Y" json:"Y,omitempty"`
	Z *int32 `protobuf:"varint,3,req,name=Z" json:"Z,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_util_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_util_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_proto_util_proto_rawDescGZIP(), []int{0}
}

func (x *Pos) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Pos) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Pos) GetZ() int32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

// 朝向
type Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *int32 `protobuf:"varint,1,req,name=X" json:"X,omitempty"`
	Z *int32 `protobuf:"varint,2,req,name=Z" json:"Z,omitempty"`
}

func (x *Dir) Reset() {
	*x = Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_util_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir) ProtoMessage() {}

func (x *Dir) ProtoReflect() protoreflect.Message {
	mi := &file_proto_util_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir.ProtoReflect.Descriptor instead.
func (*Dir) Descriptor() ([]byte, []int) {
	return file_proto_util_proto_rawDescGZIP(), []int{1}
}

func (x *Dir) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Dir) GetZ() int32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

var File_proto_util_proto protoreflect.FileDescriptor

var file_proto_util_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x03, 0x50, 0x6f,
	0x73, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x58, 0x12,
	0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x59, 0x12, 0x0c, 0x0a,
	0x01, 0x5a, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x5a, 0x22, 0x21, 0x0a, 0x03, 0x44,
	0x69, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x58,
	0x12, 0x0c, 0x0a, 0x01, 0x5a, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x5a, 0x42, 0x2d,
	0x5a, 0x2b, 0x76, 0x63, 0x73, 0x2e, 0x74, 0x61, 0x69, 0x79, 0x6f, 0x75, 0x78, 0x69, 0x2e, 0x6e,
	0x65, 0x74, 0x2f, 0x6a, 0x77, 0x73, 0x32, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e,
}

var (
	file_proto_util_proto_rawDescOnce sync.Once
	file_proto_util_proto_rawDescData = file_proto_util_proto_rawDesc
)

func file_proto_util_proto_rawDescGZIP() []byte {
	file_proto_util_proto_rawDescOnce.Do(func() {
		file_proto_util_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_util_proto_rawDescData)
	})
	return file_proto_util_proto_rawDescData
}

var file_proto_util_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_util_proto_goTypes = []interface{}{
	(*Pos)(nil), // 0: common.Pos
	(*Dir)(nil), // 1: common.Dir
}
var file_proto_util_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_util_proto_init() }
func file_proto_util_proto_init() {
	if File_proto_util_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_util_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_util_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_util_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_util_proto_goTypes,
		DependencyIndexes: file_proto_util_proto_depIdxs,
		MessageInfos:      file_proto_util_proto_msgTypes,
	}.Build()
	File_proto_util_proto = out.File
	file_proto_util_proto_rawDesc = nil
	file_proto_util_proto_goTypes = nil
	file_proto_util_proto_depIdxs = nil
}
