// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/gate.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CtlTyp int32

const (
	CtlTyp_ForceQuit CtlTyp = 0
	CtlTyp_PingCheck CtlTyp = 1
	CtlTyp_PushCheck CtlTyp = 2
)

// Enum value maps for CtlTyp.
var (
	CtlTyp_name = map[int32]string{
		0: "ForceQuit",
		1: "PingCheck",
		2: "PushCheck",
	}
	CtlTyp_value = map[string]int32{
		"ForceQuit": 0,
		"PingCheck": 1,
		"PushCheck": 2,
	}
)

func (x CtlTyp) Enum() *CtlTyp {
	p := new(CtlTyp)
	*p = x
	return p
}

func (x CtlTyp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CtlTyp) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gate_proto_enumTypes[0].Descriptor()
}

func (CtlTyp) Type() protoreflect.EnumType {
	return &file_proto_gate_proto_enumTypes[0]
}

func (x CtlTyp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CtlTyp.Descriptor instead.
func (CtlTyp) EnumDescriptor() ([]byte, []int) {
	return file_proto_gate_proto_rawDescGZIP(), []int{0}
}

type CtlRes int32

const (
	CtlRes_Ctl_Success CtlRes = 0
	CtlRes_Ctl_Fail    CtlRes = 1
)

// Enum value maps for CtlRes.
var (
	CtlRes_name = map[int32]string{
		0: "Ctl_Success",
		1: "Ctl_Fail",
	}
	CtlRes_value = map[string]int32{
		"Ctl_Success": 0,
		"Ctl_Fail":    1,
	}
)

func (x CtlRes) Enum() *CtlRes {
	p := new(CtlRes)
	*p = x
	return p
}

func (x CtlRes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CtlRes) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gate_proto_enumTypes[1].Descriptor()
}

func (CtlRes) Type() protoreflect.EnumType {
	return &file_proto_gate_proto_enumTypes[1]
}

func (x CtlRes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CtlRes.Descriptor instead.
func (CtlRes) EnumDescriptor() ([]byte, []int) {
	return file_proto_gate_proto_rawDescGZIP(), []int{1}
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacketId int32  `protobuf:"varint,1,opt,name=packetId,proto3" json:"packetId,omitempty"`
	RawData  []byte `protobuf:"bytes,4,opt,name=rawData,proto3" json:"rawData,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_proto_gate_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetPacketId() int32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *Packet) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type BatchPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acids  []string `protobuf:"bytes,1,rep,name=acids,proto3" json:"acids,omitempty"`
	Packet *Packet  `protobuf:"bytes,2,opt,name=packet,proto3" json:"packet,omitempty"`
}

func (x *BatchPacket) Reset() {
	*x = BatchPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPacket) ProtoMessage() {}

func (x *BatchPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPacket.ProtoReflect.Descriptor instead.
func (*BatchPacket) Descriptor() ([]byte, []int) {
	return file_proto_gate_proto_rawDescGZIP(), []int{1}
}

func (x *BatchPacket) GetAcids() []string {
	if x != nil {
		return x.Acids
	}
	return nil
}

func (x *BatchPacket) GetPacket() *Packet {
	if x != nil {
		return x.Packet
	}
	return nil
}

type CtlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Typ   CtlTyp `protobuf:"varint,1,opt,name=typ,proto3,enum=proto.CtlTyp" json:"typ,omitempty"`
	Param string `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
}

func (x *CtlReq) Reset() {
	*x = CtlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CtlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlReq) ProtoMessage() {}

func (x *CtlReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlReq.ProtoReflect.Descriptor instead.
func (*CtlReq) Descriptor() ([]byte, []int) {
	return file_proto_gate_proto_rawDescGZIP(), []int{2}
}

func (x *CtlReq) GetTyp() CtlTyp {
	if x != nil {
		return x.Typ
	}
	return CtlTyp_ForceQuit
}

func (x *CtlReq) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

type CtlResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res    CtlRes `protobuf:"varint,1,opt,name=res,proto3,enum=proto.CtlRes" json:"res,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CtlResp) Reset() {
	*x = CtlResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CtlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlResp) ProtoMessage() {}

func (x *CtlResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlResp.ProtoReflect.Descriptor instead.
func (*CtlResp) Descriptor() ([]byte, []int) {
	return file_proto_gate_proto_rawDescGZIP(), []int{3}
}

func (x *CtlResp) GetRes() CtlRes {
	if x != nil {
		return x.Res
	}
	return CtlRes_Ctl_Success
}

func (x *CtlResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SessionPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID    string        `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	AccountID    string        `protobuf:"bytes,2,opt,name=AccountID,proto3" json:"AccountID,omitempty"` //0:0:1001
	ClientPacket *ClientPacket `protobuf:"bytes,3,opt,name=ClientPacket,proto3" json:"ClientPacket,omitempty"`
}

func (x *SessionPacket) Reset() {
	*x = SessionPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPacket) ProtoMessage() {}

func (x *SessionPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPacket.ProtoReflect.Descriptor instead.
func (*SessionPacket) Descriptor() ([]byte, []int) {
	return file_proto_gate_proto_rawDescGZIP(), []int{4}
}

func (x *SessionPacket) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *SessionPacket) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *SessionPacket) GetClientPacket() *ClientPacket {
	if x != nil {
		return x.ClientPacket
	}
	return nil
}

var File_proto_gate_proto protoreflect.FileDescriptor

var file_proto_gate_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a,
	0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x61, 0x77, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61, 0x77, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a,
	0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x63, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x63, 0x69,
	0x64, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x3f, 0x0a, 0x06, 0x43, 0x74, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x74, 0x6c, 0x54, 0x79, 0x70, 0x52,
	0x03, 0x74, 0x79, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x42, 0x0a, 0x07, 0x43, 0x74,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x74, 0x6c, 0x52, 0x65,
	0x73, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x84,
	0x01, 0x0a, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x37, 0x0a, 0x0c,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x2a, 0x35, 0x0a, 0x06, 0x43, 0x74, 0x6c, 0x54, 0x79, 0x70, 0x12,
	0x0d, 0x0a, 0x09, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x51, 0x75, 0x69, 0x74, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x50, 0x75, 0x73, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x10, 0x02, 0x2a, 0x27, 0x0a, 0x06,
	0x43, 0x74, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x74, 0x6c, 0x5f, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x74, 0x6c, 0x5f, 0x46,
	0x61, 0x69, 0x6c, 0x10, 0x01, 0x32, 0x9e, 0x01, 0x0a, 0x04, 0x47, 0x61, 0x74, 0x65, 0x12, 0x27,
	0x0a, 0x06, 0x43, 0x74, 0x6c, 0x52, 0x70, 0x63, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x74, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x74, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x4f, 0x6e, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3d, 0x0a, 0x0d, 0x4f, 0x6e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x74, 0x61, 0x69, 0x79, 0x6f, 0x75, 0x78, 0x69, 0x2e, 0x63, 0x6e, 0x2f, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x78, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x67, 0x61, 0x6d,
	0x65, 0x78, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gate_proto_rawDescOnce sync.Once
	file_proto_gate_proto_rawDescData = file_proto_gate_proto_rawDesc
)

func file_proto_gate_proto_rawDescGZIP() []byte {
	file_proto_gate_proto_rawDescOnce.Do(func() {
		file_proto_gate_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gate_proto_rawDescData)
	})
	return file_proto_gate_proto_rawDescData
}

var file_proto_gate_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_gate_proto_goTypes = []interface{}{
	(CtlTyp)(0),           // 0: proto.CtlTyp
	(CtlRes)(0),           // 1: proto.CtlRes
	(*Packet)(nil),        // 2: proto.Packet
	(*BatchPacket)(nil),   // 3: proto.BatchPacket
	(*CtlReq)(nil),        // 4: proto.CtlReq
	(*CtlResp)(nil),       // 5: proto.CtlResp
	(*SessionPacket)(nil), // 6: proto.SessionPacket
	(*ClientPacket)(nil),  // 7: proto.ClientPacket
}
var file_proto_gate_proto_depIdxs = []int32{
	2, // 0: proto.BatchPacket.packet:type_name -> proto.Packet
	0, // 1: proto.CtlReq.typ:type_name -> proto.CtlTyp
	1, // 2: proto.CtlResp.res:type_name -> proto.CtlRes
	7, // 3: proto.SessionPacket.ClientPacket:type_name -> proto.ClientPacket
	4, // 4: proto.Gate.CtlRpc:input_type -> proto.CtlReq
	2, // 5: proto.Gate.OnPacket:input_type -> proto.Packet
	3, // 6: proto.Gate.OnBatchPacket:input_type -> proto.BatchPacket
	5, // 7: proto.Gate.CtlRpc:output_type -> proto.CtlResp
	2, // 8: proto.Gate.OnPacket:output_type -> proto.Packet
	3, // 9: proto.Gate.OnBatchPacket:output_type -> proto.BatchPacket
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_gate_proto_init() }
func file_proto_gate_proto_init() {
	if File_proto_gate_proto != nil {
		return
	}
	file_proto_packet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_gate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CtlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CtlResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gate_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gate_proto_goTypes,
		DependencyIndexes: file_proto_gate_proto_depIdxs,
		EnumInfos:         file_proto_gate_proto_enumTypes,
		MessageInfos:      file_proto_gate_proto_msgTypes,
	}.Build()
	File_proto_gate_proto = out.File
	file_proto_gate_proto_rawDesc = nil
	file_proto_gate_proto_goTypes = nil
	file_proto_gate_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GateClient is the client API for Gate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GateClient interface {
	// Sends a greeting
	//    rpc OnConnect ( OnConnectRequest) returns ( OnConnectReply) {}
	CtlRpc(ctx context.Context, in *CtlReq, opts ...grpc.CallOption) (*CtlResp, error)
	OnPacket(ctx context.Context, opts ...grpc.CallOption) (Gate_OnPacketClient, error)
	OnBatchPacket(ctx context.Context, opts ...grpc.CallOption) (Gate_OnBatchPacketClient, error)
}

type gateClient struct {
	cc grpc.ClientConnInterface
}

func NewGateClient(cc grpc.ClientConnInterface) GateClient {
	return &gateClient{cc}
}

func (c *gateClient) CtlRpc(ctx context.Context, in *CtlReq, opts ...grpc.CallOption) (*CtlResp, error) {
	out := new(CtlResp)
	err := c.cc.Invoke(ctx, "/proto.Gate/CtlRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) OnPacket(ctx context.Context, opts ...grpc.CallOption) (Gate_OnPacketClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Gate_serviceDesc.Streams[0], "/proto.Gate/OnPacket", opts...)
	if err != nil {
		return nil, err
	}
	x := &gateOnPacketClient{stream}
	return x, nil
}

type Gate_OnPacketClient interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ClientStream
}

type gateOnPacketClient struct {
	grpc.ClientStream
}

func (x *gateOnPacketClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gateOnPacketClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gateClient) OnBatchPacket(ctx context.Context, opts ...grpc.CallOption) (Gate_OnBatchPacketClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Gate_serviceDesc.Streams[1], "/proto.Gate/OnBatchPacket", opts...)
	if err != nil {
		return nil, err
	}
	x := &gateOnBatchPacketClient{stream}
	return x, nil
}

type Gate_OnBatchPacketClient interface {
	Send(*BatchPacket) error
	Recv() (*BatchPacket, error)
	grpc.ClientStream
}

type gateOnBatchPacketClient struct {
	grpc.ClientStream
}

func (x *gateOnBatchPacketClient) Send(m *BatchPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gateOnBatchPacketClient) Recv() (*BatchPacket, error) {
	m := new(BatchPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GateServer is the server API for Gate service.
type GateServer interface {
	// Sends a greeting
	//    rpc OnConnect ( OnConnectRequest) returns ( OnConnectReply) {}
	CtlRpc(context.Context, *CtlReq) (*CtlResp, error)
	OnPacket(Gate_OnPacketServer) error
	OnBatchPacket(Gate_OnBatchPacketServer) error
}

// UnimplementedGateServer can be embedded to have forward compatible implementations.
type UnimplementedGateServer struct {
}

func (*UnimplementedGateServer) CtlRpc(context.Context, *CtlReq) (*CtlResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CtlRpc not implemented")
}
func (*UnimplementedGateServer) OnPacket(Gate_OnPacketServer) error {
	return status.Errorf(codes.Unimplemented, "method OnPacket not implemented")
}
func (*UnimplementedGateServer) OnBatchPacket(Gate_OnBatchPacketServer) error {
	return status.Errorf(codes.Unimplemented, "method OnBatchPacket not implemented")
}

func RegisterGateServer(s *grpc.Server, srv GateServer) {
	s.RegisterService(&_Gate_serviceDesc, srv)
}

func _Gate_CtlRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).CtlRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Gate/CtlRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).CtlRpc(ctx, req.(*CtlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_OnPacket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GateServer).OnPacket(&gateOnPacketServer{stream})
}

type Gate_OnPacketServer interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type gateOnPacketServer struct {
	grpc.ServerStream
}

func (x *gateOnPacketServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gateOnPacketServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Gate_OnBatchPacket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GateServer).OnBatchPacket(&gateOnBatchPacketServer{stream})
}

type Gate_OnBatchPacketServer interface {
	Send(*BatchPacket) error
	Recv() (*BatchPacket, error)
	grpc.ServerStream
}

type gateOnBatchPacketServer struct {
	grpc.ServerStream
}

func (x *gateOnBatchPacketServer) Send(m *BatchPacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gateOnBatchPacketServer) Recv() (*BatchPacket, error) {
	m := new(BatchPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Gate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Gate",
	HandlerType: (*GateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CtlRpc",
			Handler:    _Gate_CtlRpc_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnPacket",
			Handler:       _Gate_OnPacket_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OnBatchPacket",
			Handler:       _Gate_OnBatchPacket_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gate.proto",
}
